import fs from 'node:fs';
import path from 'node:path';
import {parse} from '@babel/parser';
import traverseModule from '@babel/traverse';
import * as XLSX from 'xlsx';
import {root,evidence,write,walk,digest} from './inventory.mjs';
const traverse=traverseModule.default;
const inventory=JSON.parse(fs.readFileSync(path.join(root,'forensics/inventory.json'),'utf8'));
const symbols=JSON.parse(fs.readFileSync(path.join(root,'forensics/symbol-map.json'),'utf8'));
const byOld=new Map(symbols.map(s=>[s.original,s]));
const activeSource=fs.readFileSync(path.join(evidence,'assets/legacyApp-Cum0wzIn.js'),'utf8');
const activeAst=parse(activeSource,{sourceType:'module'});
const css=fs.readFileSync(path.join(evidence,'assets/index-D7j9Kx6Z.css'),'utf8');
const html=fs.readFileSync(path.join(evidence,'index.html'),'utf8');
const esc=value=>String(value??'').replaceAll('|','\\|').replaceAll('\n','<br>').replaceAll('\r','');
const table=(headers,rows)=>'| '+headers.join(' | ')+' |\n| '+headers.map(()=> '---').join(' | ')+' |\n'+rows.map(row=>'| '+row.map(esc).join(' | ')+' |').join('\n')+'\n';
const evidenceNote='\n\nEvidence offsets in these reports are JavaScript UTF-16 character offsets in the named original file, not byte offsets or reconstructed line numbers. EXACT describes surviving values and observed structures, not lost original source.\n';
let routeObject;
traverse(activeAst,{ObjectExpression(p){if(p.getFunctionParent()?.node.id?.name==='we'&&p.node.properties.some(x=>x.key?.name==='home')&&p.node.properties.some(x=>x.key?.name==='logs'))routeObject=p.node;}});
const publicSet=new Set(['home','about','teachers','programs','activities','news','media','contact','register','platform','login','completeSignup']);
const routeEntries=routeObject.properties.map(p=>({route:p.key.name,original:p.value.name||'Gi',name:byOld.get(p.value.name||'Gi')?.name,module:byOld.get(p.value.name||'Gi')?.module,start:p.start}));
write('forensics/routes.json',JSON.stringify(routeEntries,null,2));
function owner(p){let fn=p.getFunctionParent();while(fn&&!fn.node.id?.name)fn=fn.findParent(q=>q.isFunction());return fn?.node.id?.name||'(top-level)';}
function allowedRoles(route,fnSource){if(publicSet.has(route))return 'public';if(/wt\("admin"\)|role!=="admin"/.test(fnSource))return 'admin';if(/wt\("teacher"\)|role!=="teacher"/.test(fnSource))return 'teacher (see per-record guards)';if(/wt\("student"\)/.test(fnSource))return 'student';if(fnSource.includes('["admin","teacher"]')||fnSource.includes('["teacher","admin"]'))return 'admin / teacher, ownership checks';return 'authenticated; role/audience checks in renderer';}
write('docs/ROUTE_MAP.md','# Recovered hash routes\n\nEXACT: custom location.hash router, '+routeEntries.length+' route keys. No react-router, pathname router or lazy route chunks. Four aliases: cours/course → courses; connexion/connection → login. Leading/trailing slashes are removed; empty hash → home. Unknown route keys render the home content (no distinct 404 page); their body data-route can remain the unknown key.\n\n'+table(['URL','Renderer','Module','Access','Query evidence','Confidence'],routeEntries.map(r=>{
 const s=byOld.get(r.original),fn=activeSource.slice(s.start,s.end);
 const queries=[...new Set([...fn.matchAll(/\.get\("([^"\n]+)"\)/g)].map(m=>m[1]))];
 return ['#'+r.route,r.name,'src/'+r.module,allowedRoles(r.route,fn),queries.join(', ')||'None directly; shared routing helpers may add ref/id/filter parameters','EXACT route; HIGH CONFIDENCE access'];
}))+'\n## Shared parameters and redirects\n\nEXACT: entity links encode ref=entityType:entityId using URLSearchParams. Legacy id links are canonicalized with history.replaceState. Entity kinds include course, exam, questionnaire and student. scheduleId links connect lessons/exams/preparation to a schedule. Listing queries: subject, niveau, groupe, search. Other views read panel, student, participant, edit, role, scheduleMonth, settingsNiveau, niveau, groupe. See exhaustive query/attribute strings in the catalog.\n\nEXACT: token from the URL query or hash query is captured in memory, removed from the query and replaced with #completeSignup. Private-route references have a 12-hour filter, but the original helper calls an undefined safeJsonParse; the narrowly documented repair restores its intended parser. Login sends the user to admin/teacher/student; logout returns to home. Unauthorized page renderers show login/account return, not an invented route.\n'+evidenceNote);
const apiCalls=[];const literalAssets=[];const external=[];const storage=[];
for(const file of inventory.filter(f=>f.extension==='.js')){
 const source=fs.readFileSync(file.originalPath,'utf8'),ast=parse(source,{sourceType:'module'});
 const info=JSON.parse(fs.readFileSync(path.join(root,'forensics/'+file.filename+'.analysis.json'),'utf8'));
 for(const item of info.strings){
  if(/(?:^|["'`\s])\/?(?:assets|brand|brand-concepts|templates)\//.test(item.value||'')){
   for(const m of (item.value||'').matchAll(/\/?(?:assets|brand|brand-concepts|templates)\/[A-Za-z0-9_.?=\/-]+/g))literalAssets.push({file:file.filename,owner:item.owner,offset:item.offset,path:m[0]});
  }
 }
 traverse(ast,{
  CallExpression(p){const n=p.node;const arg=n.arguments[0];
   const url=tvalue(arg,source);
   if(url.startsWith('/api/'))apiCalls.push({file:file.filename,active:file.filename==='legacyApp-Cum0wzIn.js',owner:owner(p),offset:n.start,path:url,callee:source.slice(n.callee.start,n.callee.end),payload:n.arguments[1]?source.slice(n.arguments[1].start,n.arguments[1].end):'',call:source.slice(n.start,n.end)});
   if(n.callee.type==='MemberExpression'&&['localStorage','sessionStorage'].includes(n.callee.object.name))storage.push({file:file.filename,owner:owner(p),offset:n.start,call:source.slice(n.start,n.end)});
  },
  StringLiteral(p){if(/^https?:\/\//.test(p.node.value))external.push({file:file.filename,owner:owner(p),offset:p.node.start,value:p.node.value});}
 });
}
function tvalue(n,source){return n?.type==='StringLiteral'?n.value:n?.type==='TemplateLiteral'?n.quasis.map((q,i)=>q.value.cooked+(i<n.expressions.length?'${'+source.slice(n.expressions[i].start,n.expressions[i].end)+'}':'')).join(''):'';}
write('forensics/api-calls.json',JSON.stringify(apiCalls,null,2));
write('forensics/storage-calls.json',JSON.stringify(storage,null,2));
write('forensics/external-urls.json',JSON.stringify(external,null,2));
write('forensics/asset-references.json',JSON.stringify(literalAssets,null,2));
const activeCalls=apiCalls.filter(c=>c.active);
write('docs/API_MAP.md','# API forensics\n\nEXACT: relative /api paths; base is window origin. Browser-native fetch, not Axios. All JSON POSTs use credentials: same-origin, Content-Type: application/json and JSON.stringify(payload); GETs use credentials: same-origin. No Authorization/Bearer header is emitted. Both helpers parse JSON, fall back to {}, and throw reason || detail || error || the original Arabic backend error for non-OK responses. Server status codes and cookie attributes are UNKNOWN from dist.\n\n'+table(['Path','Method','Caller','Payload / query','Source offset','Confidence'],activeCalls.map(c=>[c.path,c.callee==='Cc'?'GET':'POST',byOld.get(c.owner)?.name||c.owner,'`'+c.payload+'`',c.offset,'EXACT']))+'\n## Response and failure handling\n\n'+activeCalls.map(c=>{const m=byOld.get(c.owner);return `### ${c.path} — ${m?.name||c.owner}\n\nEXACT invocation: \`${c.call}\`.\n\nReadable response/error handling: [${m?.name||c.owner}](../src/${m?.module||'services/http.js'}). Original active chunk offset ${c.offset}.\n`;}).join('\n')+'\nNon-API fetch: production modulepreload helper, bulletin image-to-data-URL conversion. External URLs include Google Maps iframe, YouTube embed handling and user-provided meeting/media URLs; these are not new backend endpoints. All four legacy versions were scanned; inactive-only/changed calls remain separately identified in forensics/api-calls.json.\n\nTesting uses an isolated intercepted API fixture only; it is never bundled into src/build and does not claim to implement the real backend.\n'+evidenceNote);
write('docs/INDEX_ANALYSIS.md','# index.html analysis\n\nEXACT surviving document:\n\n```html\n'+html+'\n```\n\n'+table(['Feature','Evidence','Confidence'],[
 ['Mount','div#root','EXACT'],['Language / direction','ar / rtl','EXACT'],['Charset','UTF-8','EXACT'],['JS entry','/assets/index-Bgp60kJC.js, module + crossorigin','EXACT'],['CSS entry','/assets/index-D7j9Kx6Z.css, crossorigin','EXACT'],['Favicon','/assets/platform-logo-mark.png','EXACT'],['Preloads','No preload/modulepreload tags in HTML; runtime polyfill in entry','EXACT'],['Web fonts','No external font requests or @font-face; system fallback stack','EXACT'],['External scripts / styles','None in HTML','EXACT'],['Analytics / structured data','None in HTML','EXACT'],['SEO','Arabic title, description, viewport','EXACT'],['OpenGraph / Twitter / canonical','No tags present','EXACT']
 ])+'\nReconstruction preserves the document metadata verbatim, replacing only the compiled script/style tags with the source entry; CSS imports through main.jsx.\n');
const tokens=[...css.matchAll(/(--[\w-]+)\s*:\s*([^;}]+)/g)].map(m=>[m[1],m[2].trim()]);
const media=[...new Set([...css.matchAll(/@media\s*([^{}]+)\{/g)].map(m=>m[1]))];
const fonts=[...new Set([...css.matchAll(/font-family\s*:\s*([^;}]+)/g)].map(m=>m[1]))];
const animations=[...new Set([...css.matchAll(/@keyframes\s+([\w-]+)/g)].map(m=>m[1]))];
const radii=[...new Set([...css.matchAll(/border-radius\s*:\s*([^;}]+)/g)].map(m=>m[1]))];
write('docs/STYLE_ANALYSIS.md','# Style analysis\n\nEXACT: the entire 117292-byte stylesheet was read. src/styles/production.css is its readable formatting, preserving rule/declaration order and values; no redesign, reset, utility framework or additional CSS was added. forensics/beautified_bundles contains the independent analysis copy.\n\n## Tokens\n\n'+table(['Variable','Value'],tokens)+'\n## Typography\n\n'+fonts.map(f=>'- EXACT: `'+f+'`').join('\n')+'\n\nNo font binaries or @font-face rules survive. Actual rendering depends on installed fonts (UNKNOWN original machine font availability). Body: 16px, line-height 1.8, RTL/right-aligned.\n\n## Breakpoints\n\n'+media.map(f=>'- EXACT: `'+f+'`').join('\n')+'\n\n## Animation\n\n'+animations.map(f=>'- EXACT: `'+f+'`').join('\n')+'\n\n## Layout and components\n\nEXACT: grid/flex layouts, sticky header, responsive navigation, panels/cards, nested template-based forms, table search and pagination, draggable account sidebar, toast region, gallery, exam/session forms and print documents. Styles contain successive overrides; keeping their order is essential. Common dimensions: --container min(1180px, calc(100% - 32px)); nav shell max 1280px; section/footer max 1120px. Border radii include '+radii.map(r=>'`'+r+'`').join(', ')+'.\n\nSpacing, shadows, color literals and every selector remain accessible in the readable CSS, not approximated into a new scale. Print-document styles also exist in generated HTML templates in bulletins.js and account/teaching modules.\n');
write('docs/BRAND_ANALYSIS.md','# Branding analysis\n\nEXACT: dist/brand/ is absent. Production branding is under assets/. The institution is مشيخة التعليم الزيتوني وفروعه; the shell also uses Enseignement Zitouni. No separate brand guide, font file, SVG or design export survives.\n\n'+table(['Resource','Dimensions','Observed use','Confidence'],inventory.filter(f=>f.extension==='.png').map(f=>[f.relative,f.dimensions,f.bundleReferences.length?'Literal entry/application/CSS references; see ASSET_MAP.md':'No literal reference found','EXACT metadata; HIGH CONFIDENCE purpose']))+'\n## Identity\n\nEXACT CSS tokens: olive #68752A / #3F4A1D, turquoise #1689A8 / #08657A, brown #704522, yellow #F2D14B, antique gold #C9A348, burgundy #7C2424, ivory #FAF8F1 and cream #F4EEDC. Visual inspection: institutional emblems, a minaret/olive-branch mark, geometric Islamic pattern, green manuscript-like hero, gold details, rounded panels. Motif interpretation is INFERRED; paths/colors are EXACT.\n\nMain logo and platform-logo-full are byte-identical; bulletin-header-left and platform-logo-mark are byte-identical. Both logos in the header and the report-card signature are preserved. Unreferenced duplicate branding files remain available in public, but are not newly inserted in the UI.\n');
write('docs/AUTH_FLOW.md','# Authentication recovery\n\nEXACT: login, logout, profile update, password change, activation invite/completion, password verification before destructive UI actions and avatar update exist. The backend session is requested at startup; browser fetch uses same-origin credentials. No frontend JWT decoder, accessToken, refreshToken, Bearer header, localStorage auth token or refresh endpoint is evidenced. Cookies are implied by credentials/session behavior (HIGH CONFIDENCE); cookie names, expiry, HttpOnly/SameSite flags and server authorization are UNKNOWN.\n\nCurrent user ID/object and persistence eligibility live in memory. State loads before session restoration; authenticated users trigger a second load. Disabled users are excluded. Admin initialization seeds surviving demo records and queues state persistence exactly as the build does. Demo literals are not newly invented users and do not prove real backend credentials.\n\nRoles: student, teacher, admin. Each renderer and content helper retains its original role, level, group, program, publication and ownership checks. The UI is not a replacement for server authorization. Unauthenticated private views render login. A signed-in visit to login/register renders the account return card.\n\nLogin POST body: email (trimmed/lowercase) and password. Disabled, unactivated and throttled backend messages map to the original Arabic alerts; other login failures use the original generic alert. Successful login restores state, records activity, shows a toast and changes the hash to the role dashboard.\n\nActivation token may enter through page query or hash query; it is moved to in-memory state and removed from the URL before #completeSignup. The invite resolves through /api/activation-invite, then the completion form validates password and confirmation before /api/activation-complete. The inferred safeJsonParse repair affects private reference storage/attachment editing, not authentication policy.\n\nLocal storage is used only for draggable sidebar coordinates. Session storage is read for private entity references. No additional persistence or auth library was introduced.\n');
write('docs/DEPENDENCY_ANALYSIS.md','# Dependency analysis\n\n'+table(['Package / capability','Version','Evidence','Confidence'],[
 ['react','19.2.8','B.version literal in each entry; hooks and React element symbols','EXACT'],['react-dom','19.2.8','rendererPackageName/react-dom, version literals, createRoot','EXACT'],['scheduler','React dependency; version not retained','unstable_scheduleCallback / priority scheduling in entry','HIGH CONFIDENCE package; UNKNOWN original exact version'],['vite','Original version UNKNOWN; reconstruction pins 7.3.1','modulepreload polyfill, vite:preloadError, dynamic import wrapper, hashed assets','HIGH CONFIDENCE tool; INFERRED reconstruction version'],['xlsx (SheetJS CE)','Original exact version UNKNOWN; reconstruction 0.18.5','Contiguous spreadsheet vendor at offsets 3436–368558; CFB, SheetJS markers; xn reader and $S.sheet_to_json used by importAccounts','HIGH CONFIDENCE identity; INFERRED package version'],['cfb / crc-32','1.2.2 / 1.2.0 runtime literals','Embedded spreadsheet vendor version literals','EXACT retained literals; HIGH CONFIDENCE attribution'],['Router','Native hash router','location.hash/hashchange/history.replaceState','EXACT; no router package'],['HTTP','Native fetch','same-origin GET and JSON POST wrappers','EXACT; no axios'],['State','Module-scoped JavaScript state + backend items','Lo cached strings, globals and /api/app-state','EXACT; no Redux/Zustand'],['UI / CSS framework / CSS-in-JS','None detected','Native markup, authored CSS, React shell','HIGH CONFIDENCE absence'],['Icons','Characters, CSS and PNG logos','No icon component/library signatures','HIGH CONFIDENCE'],['Animations','CSS + native timers','@keyframes; gallery and exam intervals','EXACT'],['Forms / validation','Native FormData, validity and regex','submit event delegation and password regex checks','EXACT'],['i18n','Literal Arabic/French with Intl','No translation library or locale chunks','EXACT'],['Charts','Native template/CSS calculations','Questionnaire checklist bars, statistics, grade tables','HIGH CONFIDENCE'],['Dates','Date / Intl.DateTimeFormat','ar-TN/fr-FR formatting','EXACT'],['Auth package','None detected','Session API + role checks','HIGH CONFIDENCE'],['@babel/parser, traverse, generator, types','7.28.5','Reconstruction necessity: lexical AST extraction/renaming/module splitting/provenance','INFERRED tooling, not original app dependency'],['prettier','3.6.2','Readable analysis/source formatting','INFERRED tooling necessity'],['playwright','1.58.2','Requested route/interaction/browser comparison','INFERRED testing necessity'],['pngjs','7.0.0','Requested pixel comparison of screenshots','INFERRED testing necessity']
 ])+'\nOnly React/ReactDOM/SheetJS are application dependencies. Framework vendor internals were replaced by package imports; they are not copied into src. No prior project package manifest or source was consulted.\n\nPackage source references: [React versions](https://react.dev/versions), [Vite documentation](https://vite.dev/guide/), [SheetJS installation](https://docs.sheetjs.com/docs/getting-started/installation/frameworks/). SheetJS documents that npm 0.18.5 is an older release; this reconstruction pins it as a compatibility choice, not a claim that it is current or that the original exact version is proved. Upgrading is separate work requiring import-format regression tests.\n\n`package-lock.json` locks resolved versions. Remaining transitive entries are package-manager resolution, not claimed original direct dependencies.\n');
write('docs/UI_COMPONENT_MAP.md','# Page and component catalog\n\nReact App/Header shell plus 680 recovered application functions in 46 domain modules. All original function bodies survive subject to scoped identifier renaming, explicit state access and safe statement expansion. Names/module boundaries are INFERRED. Reused literal text and markup are EXACT; runtime behavior is HIGH CONFIDENCE and browser-tested.\n\n'+table(['Original symbol','Readable function','Source module','Original start','Confidence'],symbols.map(s=>[s.original,s.name,'src/'+s.module,s.start,s.confidence]))+'\n## UI families\n\nPages: public institution pages, learning listings, lesson/exam/questionnaire session and preview/editor views, account activation/profile/login, student/teacher/admin dashboards, levels/groups/subjects/users, schedule, absences, grades/results/bulletins/logs. Shared pieces: header/footer/sidebar, cards, filters/search, paginated tables, question builders, file viewers, registration/account forms, toasts, gallery, charts and print templates. Native confirm/prompt windows and HTML details are retained; no modal library is added.\n'+evidenceNote);
// Full literal catalogs include all eight bundles; user-facing candidates are separately labeled.
const catalog=new Map();let literalCount=0;
for(const file of inventory.filter(f=>f.extension==='.js')){
 const info=JSON.parse(fs.readFileSync(path.join(root,'forensics/'+file.filename+'.analysis.json'),'utf8'));
 for(const s of info.strings){literalCount++;const value=s.value??s.raw??'';if(!value.trim())continue;
  const isVendor=file.filename.startsWith('index-')?s.offset<193000:s.offset>=3436&&s.offset<(file.filename==='legacyApp-Cum0wzIn.js'?368558:350000);
  if(!/[\u0600-\u06ff]/.test(value)&&!(file.filename.startsWith('index-')&&s.offset>193000)||isVendor&&!/[\u0600-\u06ff]/.test(value))continue;
  const entry=catalog.get(value)||{value,references:[]};entry.references.push({file:file.filename,owner:s.owner,offset:s.offset,active:['index-Bgp60kJC.js','legacyApp-Cum0wzIn.js'].includes(file.filename)});catalog.set(value,entry);
 }
}
write('forensics/text-catalog.json',JSON.stringify([...catalog.values()],null,2));
write('docs/TEXT_CATALOG.md','# Text catalog\n\nEXACT decoded strings/template fragments; wording is not translated or corrected. '+literalCount+' string/template occurrences were extracted from all 8 JS bundles into their *.analysis.json files. '+catalog.size+' distinct Arabic-bearing or React-shell candidates are listed below, including markup when part of a template. Some are validation/error/log strings rather than visible text in every state. Dynamic text supplied by the backend is UNKNOWN. The complete unfiltered string extraction retains French/English machine and library strings as well.\n\nLanguages: Arabic (including Tunisian wording), French navigation/date/report labels, English backend/developer messages. No i18n package is detected. Inactive-only wording is not added to the active app.\n\n'+table(['Exact string / template fragment (JSON escaped)','References'],[...catalog.values()].map(s=>['`'+JSON.stringify(s.value).replaceAll('`','&#96;')+'`',s.references.map(r=>`${r.file}:${r.offset} ${r.active?'active':'inactive'}`).join('; ')]))+evidenceNote);
write('docs/ENVIRONMENT.md','# Environment recovery\n\nEXACT: no import.meta.env, VITE_*, PUBLIC_*, API_URL or API base configuration names survive in application code. process/environment tests in spreadsheet and framework vendor code do not establish original project env variables. Compilation may have erased original variable names (UNKNOWN).\n\nAll application API calls use relative same-origin paths. .env.example contains only BACKEND_ORIGIN, an explicitly INFERRED, optional development proxy target introduced for running the recovered source against the real backend. It is not exposed in client code and has no default invented origin/port. Production deployment must serve /api on the same origin or configure its own reverse proxy. No secrets are included.\n\nNode 24.21.0 and npm 11.19.0 were used for validation. On this Windows machine PowerShell blocks npm.ps1, so npm.cmd is used. Build outputs go only to frontend_reconstructed/build.\n');
const knownFiles=new Set(inventory.map(f=>f.relative));
const missing=[...new Set(literalAssets.filter(a=>a.file==='legacyApp-Cum0wzIn.js'||a.file==='index-Bgp60kJC.js').map(a=>a.path.replace(/^\//,'').split('?')[0]).filter(a=>!knownFiles.has(a)))];
write('forensics/missing-assets.json',JSON.stringify(missing,null,2));
const workbook=XLSX.read(fs.readFileSync(path.join(evidence,'templates/exemple-import-comptes.xlsx')),{type:'buffer'});
const workbookSummary=workbook.SheetNames.map(name=>({name,range:workbook.Sheets[name]['!ref'],rows:XLSX.utils.sheet_to_json(workbook.Sheets[name],{header:1,defval:''}),formulaCells:Object.entries(workbook.Sheets[name]).filter(([k,v])=>!k.startsWith('!')&&v.f).map(([cell,v])=>({cell,formula:v.f}))}));
write('forensics/account-template.json',JSON.stringify(workbookSummary,null,2));
write('docs/ACCOUNT_IMPORT_TEMPLATE.md','# Account-import workbook\n\nEXACT: read-only inspection of the surviving XLSX using the same library family used by the application. The file was copied byte-for-byte to public/templates; it was not rewritten. SHA-256: '+inventory.find(f=>f.extension==='.xlsx').sha256+'.\n\n'+table(['Sheet','Range','Rows','Formula count'],workbookSummary.map(s=>[s.name,s.range,s.rows.length,s.formulaCells.length]))+'\nFull cells/header evidence: forensics/account-template.json. Import mapping, field aliases, level/group matching, role normalization, payment flags, duplicate checks and activation behavior are in src/services/account-import.js.\n');
write('docs/UNCERTAINTIES.md','# Uncertainties and limitations\n\n- UNKNOWN: original source filenames, directories, local variable names, comments, TypeScript types, package.json and build configuration. No source maps exist. exact_recovered_sources contains an explanatory README only.\n- INFERRED: source/module names, shared state object, lexical variable names, React Header boundary, Vite 7.3.1 config and optional development proxy. Each recovered function maps back to its active-bundle offset.\n- HIGH CONFIDENCE: React 19.2.8 hybrid shell + imperative hash application; Vite identity. EXACT: React/ReactDOM version literals. UNKNOWN: original Vite/SheetJS exact versions; xlsx 0.18.5 is the reconstruction compatibility selection.\n- EXACT: the active graph is selected from index.html; three other entry/legacy pairs remain evidence, not feature sources to merge.\n- EXACT: brand/ and brand-concepts/ are absent. Their requested analyses explicitly report absence.\n- UNKNOWN: actual backend database content, cookie policies, server-side roles, working SMTP/Zoom settings, private uploaded materials and live API status. Backend folder was not read or reused. Tests intercept requests and never send real email, create real meetings or edit a real database.\n- EXACT: original safeJsonParse is undefined at three call sites. A small INFERRED parser repair is documented and tested; without it removing/saving attachments throws. The original route-reference reader catches this error and falls back to {}.\n- EXACT missing original asset paths: '+missing.map(m=>'`'+m+'`').join(', ')+'. These chiefly affect enrollment/payroll print logos. No fabricated replacements are silently inserted.\n- UNKNOWN: remote/user-supplied images, videos, PDFs and iframes when URLs/records are absent. Google Maps/external resources are blocked in isolated comparison tests.\n- EXACT: system-font fallbacks only; pixel fidelity is verified on the current test machine, not all OS/font combinations.\n- INFERRED module boundaries preserve the original shared-state architecture and can contain circular function imports. No initialization runs at module top level beyond inert defaults/state; bootstrap preserves original execution order.\n- Original pre-existing behavior is preserved: sample literals/admin demo seeding, unknown-route home fallback, native password prompts and client-generated reports. Not claimed to be a new backend or a redesign.\n');
const alternatives=inventory.filter(f=>f.extension==='.js').map(file=>{
const info=JSON.parse(fs.readFileSync(path.join(root,'forensics/'+file.filename+'.analysis.json'),'utf8'));return[file.filename,file.size,info.declarations.length,info.strings.length,info.imports.join(', ')||'none',file.filename==='index-Bgp60kJC.js'||file.filename==='legacyApp-Cum0wzIn.js'?'ACTIVE':'INACTIVE from current HTML'];});
write('docs/BUNDLE_ANALYSIS.md','# Bundle analysis\n\nAll eight JavaScript files and the stylesheet were parsed/formatted for analysis. Original hashes and links are in the inventory. No bundle was loaded as the reconstructed application.\n\n'+table(['Bundle','Bytes','Top-level declarations/statements','String occurrences','Lazy imports','Reachability'],alternatives)+'\n## Boundaries\n\nActive entry embeds React, scheduler and ReactDOM before the final ch app shell. Its lone lazy import is legacyApp-Cum0wzIn.js. The active legacy chunk starts with audience/identifier utilities (offsets 0–3436), then SheetJS vendor code (3436–368558), then default data, shared state, event registration, pages and domain functions. Only two vendor symbols cross into the app: xn (workbook read) and $S.sheet_to_json. They are replaced with xlsx imports.\n\nAll 680 app functions and 75 state bindings are accounted for by symbol-map.json/state-map.json. The alternate bundles are all inspected, including their strings, I/O and declarations; no assumption that the largest/latest filename is production was needed. Literal asset and API cross-reference reports include every version.\n');
console.log(JSON.stringify({routes:routeEntries.length,activeApiCalls:activeCalls.length,endpoints:new Set(activeCalls.map(c=>c.path.split('?')[0])).size,textCandidates:catalog.size,missingAssets:missing,workbookSheets:workbookSummary.map(s=>({name:s.name,range:s.range}))},null,2));
